<?php
/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

/**
 * API
 */
interface ServingIf
{
    /**
     * 词典管理
     * 
     * @param \Data $request
     * @return \Data Clause Data Bundle
     * 
     */
    public function postCustomDict(\Data $request);
    /**
     * @param \Data $request
     * @return \Data Clause Data Bundle
     * 
     */
    public function putCustomDict(\Data $request);
    /**
     * @param \Data $request
     * @return \Data Clause Data Bundle
     * 
     */
    public function getCustomDicts(\Data $request);
    /**
     * @param \Data $request
     * @return \Data Clause Data Bundle
     * 
     */
    public function getCustomDict(\Data $request);
    /**
     * @param \Data $request
     * @return \Data Clause Data Bundle
     * 
     */
    public function delCustomDict(\Data $request);
    /**
     * @param \Data $request
     * @return \Data Clause Data Bundle
     * 
     */
    public function postSysDict(\Data $request);
    /**
     * @param \Data $request
     * @return \Data Clause Data Bundle
     * 
     */
    public function putSysDict(\Data $request);
    /**
     * @param \Data $request
     * @return \Data Clause Data Bundle
     * 
     */
    public function getSysDicts(\Data $request);
    /**
     * @param \Data $request
     * @return \Data Clause Data Bundle
     * 
     */
    public function getSysDict(\Data $request);
    /**
     * @param \Data $request
     * @return \Data Clause Data Bundle
     * 
     */
    public function refSysDict(\Data $request);
    /**
     * @param \Data $request
     * @return \Data Clause Data Bundle
     * 
     */
    public function unrefSysDict(\Data $request);
    /**
     * @param \Data $request
     * @return \Data Clause Data Bundle
     * 
     */
    public function myDicts(\Data $request);
    /**
     * @param \Data $request
     * @return \Data Clause Data Bundle
     * 
     */
    public function mySysdicts(\Data $request);
    /**
     * @param \Data $request
     * @return \Data Clause Data Bundle
     * 
     */
    public function putDictWord(\Data $request);
    /**
     * @param \Data $request
     * @return \Data Clause Data Bundle
     * 
     */
    public function getDictWords(\Data $request);
    /**
     * @param \Data $request
     * @return \Data Clause Data Bundle
     * 
     */
    public function delDictWord(\Data $request);
    /**
     * @param \Data $request
     * @return \Data Clause Data Bundle
     * 
     */
    public function hasDictWord(\Data $request);
    /**
     * 意图
     * 
     * @param \Data $request
     * @return \Data Clause Data Bundle
     * 
     */
    public function postIntent(\Data $request);
    /**
     * @param \Data $request
     * @return \Data Clause Data Bundle
     * 
     */
    public function putIntent(\Data $request);
    /**
     * @param \Data $request
     * @return \Data Clause Data Bundle
     * 
     */
    public function getIntents(\Data $request);
    /**
     * @param \Data $request
     * @return \Data Clause Data Bundle
     * 
     */
    public function getIntent(\Data $request);
    /**
     * @param \Data $request
     * @return \Data Clause Data Bundle
     * 
     */
    public function delIntent(\Data $request);
    /**
     * @param \Data $request
     * @return \Data Clause Data Bundle
     * 
     */
    public function postUtter(\Data $request);
    /**
     * @param \Data $request
     * @return \Data Clause Data Bundle
     * 
     */
    public function putUtter(\Data $request);
    /**
     * @param \Data $request
     * @return \Data Clause Data Bundle
     * 
     */
    public function getUtters(\Data $request);
    /**
     * @param \Data $request
     * @return \Data Clause Data Bundle
     * 
     */
    public function getUtter(\Data $request);
    /**
     * @param \Data $request
     * @return \Data Clause Data Bundle
     * 
     */
    public function delUtter(\Data $request);
    /**
     * @param \Data $request
     * @return \Data Clause Data Bundle
     * 
     */
    public function postSlot(\Data $request);
    /**
     * @param \Data $request
     * @return \Data Clause Data Bundle
     * 
     */
    public function putSlot(\Data $request);
    /**
     * @param \Data $request
     * @return \Data Clause Data Bundle
     * 
     */
    public function getSlots(\Data $request);
    /**
     * @param \Data $request
     * @return \Data Clause Data Bundle
     * 
     */
    public function getSlot(\Data $request);
    /**
     * @param \Data $request
     * @return \Data Clause Data Bundle
     * 
     */
    public function delSlot(\Data $request);
    /**
     * 对话管理
     * 
     * @param \Data $request
     * @return \Data Clause Data Bundle
     * 
     */
    public function train(\Data $request);
    /**
     * @param \Data $request
     * @return \Data Clause Data Bundle
     * 
     */
    public function status(\Data $request);
    /**
     * @param \Data $request
     * @return \Data Clause Data Bundle
     * 
     */
    public function devver(\Data $request);
    /**
     * @param \Data $request
     * @return \Data Clause Data Bundle
     * 
     */
    public function prover(\Data $request);
    /**
     * @param \Data $request
     * @return \Data Clause Data Bundle
     * 
     */
    public function version(\Data $request);
    /**
     * @param \Data $request
     * @return \Data Clause Data Bundle
     * 
     */
    public function chat(\Data $request);
    /**
     * @param \Data $request
     * @return \Data Clause Data Bundle
     * 
     */
    public function online(\Data $request);
    /**
     * @param \Data $request
     * @return \Data Clause Data Bundle
     * 
     */
    public function offline(\Data $request);
    /**
     * @param \Data $request
     * @return \Data Clause Data Bundle
     * 
     */
    public function putSession(\Data $request);
    /**
     * @param \Data $request
     * @return \Data Clause Data Bundle
     * 
     */
    public function getSession(\Data $request);
}
