/***************************************************************************
 *
 * Copyright (c) 2019 Chatopera.Inc, Inc. All Rights Reserved
 *
 **************************************************************************/

/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef _CHATOPERA_BOT_SYSDICTS_SERVING_H_
#define _CHATOPERA_BOT_SYSDICTS_SERVING_H_

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "server_types.h"

namespace chatopera {
namespace bot {
namespace sysdicts {

#ifdef _MSC_VER
#pragma warning( push )
#pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class ServingIf {
 public:
  virtual ~ServingIf() {}
  virtual void label(Data& _return, const Data& request) = 0;
};

class ServingIfFactory {
 public:
  typedef ServingIf Handler;

  virtual ~ServingIfFactory() {}

  virtual ServingIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(ServingIf* /* handler */) = 0;
};

class ServingIfSingletonFactory : virtual public ServingIfFactory {
 public:
  ServingIfSingletonFactory(const ::apache::thrift::stdcxx::shared_ptr<ServingIf>& iface) : iface_(iface) {}
  virtual ~ServingIfSingletonFactory() {}

  virtual ServingIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(ServingIf* /* handler */) {}

 protected:
  ::apache::thrift::stdcxx::shared_ptr<ServingIf> iface_;
};

class ServingNull : virtual public ServingIf {
 public:
  virtual ~ServingNull() {}
  void label(Data& /* _return */, const Data& /* request */) {
    return;
  }
};

typedef struct _Serving_label_args__isset {
  _Serving_label_args__isset() : request(false) {}
  bool request : 1;
} _Serving_label_args__isset;

class Serving_label_args {
 public:

  Serving_label_args(const Serving_label_args&);
  Serving_label_args& operator=(const Serving_label_args&);
  Serving_label_args() {
  }

  virtual ~Serving_label_args() throw();
  Data request;

  _Serving_label_args__isset __isset;

  void __set_request(const Data& val);

  bool operator == (const Serving_label_args & rhs) const {
    if (!(request == rhs.request))
      return false;

    return true;
  }
  bool operator != (const Serving_label_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Serving_label_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Serving_label_pargs {
 public:


  virtual ~Serving_label_pargs() throw();
  const Data* request;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Serving_label_result__isset {
  _Serving_label_result__isset() : success(false) {}
  bool success : 1;
} _Serving_label_result__isset;

class Serving_label_result {
 public:

  Serving_label_result(const Serving_label_result&);
  Serving_label_result& operator=(const Serving_label_result&);
  Serving_label_result() {
  }

  virtual ~Serving_label_result() throw();
  Data success;

  _Serving_label_result__isset __isset;

  void __set_success(const Data& val);

  bool operator == (const Serving_label_result & rhs) const {
    if (!(success == rhs.success))
      return false;

    return true;
  }
  bool operator != (const Serving_label_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Serving_label_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Serving_label_presult__isset {
  _Serving_label_presult__isset() : success(false) {}
  bool success : 1;
} _Serving_label_presult__isset;

class Serving_label_presult {
 public:


  virtual ~Serving_label_presult() throw();
  Data* success;

  _Serving_label_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class ServingClient : virtual public ServingIf {
 public:
  ServingClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  ServingClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot, oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot, prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_ = iprot;
    poprot_ = oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void label(Data& _return, const Data& request);
  void send_label(const Data& request);
  void recv_label(Data& _return);
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class ServingProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::apache::thrift::stdcxx::shared_ptr<ServingIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (ServingProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_label(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  ServingProcessor(::apache::thrift::stdcxx::shared_ptr<ServingIf> iface) :
    iface_(iface) {
    processMap_["label"] = &ServingProcessor::process_label;
  }

  virtual ~ServingProcessor() {}
};

class ServingProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  ServingProcessorFactory(const ::apache::thrift::stdcxx::shared_ptr< ServingIfFactory >& handlerFactory) :
    handlerFactory_(handlerFactory) {}

  ::apache::thrift::stdcxx::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::apache::thrift::stdcxx::shared_ptr< ServingIfFactory > handlerFactory_;
};

class ServingMultiface : virtual public ServingIf {
 public:
  ServingMultiface(std::vector<apache::thrift::stdcxx::shared_ptr<ServingIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~ServingMultiface() {}
 protected:
  std::vector<apache::thrift::stdcxx::shared_ptr<ServingIf> > ifaces_;
  ServingMultiface() {}
  void add(::apache::thrift::stdcxx::shared_ptr<ServingIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void label(Data& _return, const Data& request) {
    size_t sz = ifaces_.size();
    size_t i = 0;

    for (; i < (sz - 1); ++i) {
      ifaces_[i]->label(_return, request);
    }

    ifaces_[i]->label(_return, request);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class ServingConcurrentClient : virtual public ServingIf {
 public:
  ServingConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  ServingConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot, oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot, prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_ = iprot;
    poprot_ = oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void label(Data& _return, const Data& request);
  int32_t send_label(const Data& request);
  void recv_label(Data& _return, const int32_t seqid);
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _MSC_VER
#pragma warning( pop )
#endif

}
}
} // namespace

#endif
